management:
  server:
    # different port for actuator endpoint. This might not be exposed outside of k8s cluster
    port: 9091
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: livenessstate,readinessstate
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  application:
    name: meetup
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost}:${DB_PORT:5432}/${DB_NAME:mydatabase}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER_CLASS:org.postgresql.Driver}
    hikari:
      minimumIdle: ${MINIMUM_IDLE:3}
      maximumPoolSize: ${MAXIMUM_POOL_SIZE:10}
      idleTimeout: ${IDLE_TIMEOUT:60000}

  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog-root.yaml'
server:
  port: 8082

org:
  jobrunr:
    database:
      skip-create: false
      table-prefix: _job_runr
    dashboard:
      enabled: true
    port: 8000
    background-job-server:
      enabled: true
      poll-interval-in-seconds: 5

job-scheduler:
  time-to-wait: 3600